# Generated by Django 5.2.7 on 2025-11-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='freqCardi',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='dados',
            name='leitura_h',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dados',
            name='oxigenacao',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='dados',
            name='presCardi',
            field=models.CharField(max_length=5),
        ),
    ]
